/**
 * SQL 自动补全配置模块
 *
 * 按数据库类型（DatabaseType）分离关键字、内置函数、数据类型和代码片段配置。
 * 新增数据库类型时只需添加一条记录，补全提供者无需修改。
 */
import type { DatabaseType } from '@/types/ipc'

/** 补全项类型枚举 */
export type CompletionItemKind = 'keyword' | 'function' | 'datatype' | 'snippet'

/** 代码片段定义 */
export interface SqlSnippet {
  /** 显示标签 */
  label: string
  /** 插入文本（支持 $1, $2 占位符） */
  insertText: string
  /** 描述 */
  description: string
}

/** 单数据库类型的补全配置 */
export interface SqlCompletionConfig {
  /** SQL 关键字（DML、DDL、DCL 等） */
  keywords: string[]
  /** 内置函数名 */
  functions: string[]
  /** 数据类型 */
  dataTypes: string[]
  /** 代码片段 */
  snippets: SqlSnippet[]
}

// ─── PostgreSQL 补全配置 ───

const postgresqlKeywords: string[] = [
  // DML
  'SELECT',
  'INSERT',
  'UPDATE',
  'DELETE',
  'MERGE',
  'RETURNING',
  'FROM',
  'WHERE',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'FULL',
  'OUTER',
  'CROSS',
  'NATURAL',
  'ON',
  'USING',
  'AS',
  'INTO',
  'VALUES',
  'SET',
  'DEFAULT',
  'GROUP',
  'BY',
  'ORDER',
  'ASC',
  'DESC',
  'NULLS',
  'FIRST',
  'LAST',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'FETCH',
  'NEXT',
  'ROWS',
  'ONLY',
  'WITH',
  'TIES',
  'UNION',
  'INTERSECT',
  'EXCEPT',
  'ALL',
  'DISTINCT',
  'DISTINCT ON',
  'LATERAL',
  'TABLESAMPLE',
  'BERNOULLI',
  'SYSTEM',
  // DDL
  'CREATE',
  'ALTER',
  'DROP',
  'TRUNCATE',
  'RENAME',
  'ADD',
  'COLUMN',
  'TABLE',
  'VIEW',
  'INDEX',
  'SEQUENCE',
  'SCHEMA',
  'DATABASE',
  'FUNCTION',
  'PROCEDURE',
  'TRIGGER',
  'RULE',
  'TYPE',
  'DOMAIN',
  'CONSTRAINT',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'UNIQUE',
  'CHECK',
  'NOT',
  'NULL',
  'CASCADE',
  'RESTRICT',
  'IF',
  'EXISTS',
  'TEMPORARY',
  'TEMP',
  'UNLOGGED',
  'INHERITS',
  'PARTITION',
  'BY',
  'RANGE',
  'LIST',
  'HASH',
  'MATERIALIZED',
  'REFRESH',
  'CONCURRENTLY',
  'TABLESPACE',
  'OWNER',
  'GRANT',
  'REVOKE',
  'PRIVILEGES',
  'TO',
  'WITH',
  'GRANT',
  'OPTION',
  // DCL
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'SAVEPOINT',
  'RELEASE',
  'LOCK',
  'SHARE',
  'EXCLUSIVE',
  'NOWAIT',
  'ACCESS',
  // 其他
  'EXPLAIN',
  'ANALYZE',
  'VERBOSE',
  'COSTS',
  'BUFFERS',
  'TIMING',
  'FORMAT',
  'COPY',
  'VACUUM',
  'ANALYZE',
  'REINDEX',
  'CLUSTER',
  'SHOW',
  'SET',
  'RESET',
  'LISTEN',
  'NOTIFY',
  'DO',
  'DECLARE',
  'PERFORM',
  'EXECUTE',
  'PREPARE',
  'DEALLOCATE',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'COALESCE',
  'NULLIF',
  'GREATEST',
  'LEAST',
  'CAST',
  'BETWEEN',
  'IN',
  'LIKE',
  'ILIKE',
  'SIMILAR',
  'IS',
  'ISNULL',
  'NOTNULL',
  'AND',
  'OR',
  'XOR',
  'TRUE',
  'FALSE',
  'RECURSIVE',
  'WINDOW',
  'OVER',
  'PARTITION',
  'RANGE',
  'ROWS',
  'BETWEEN',
  'UNBOUNDED',
  'PRECEDING',
  'FOLLOWING',
  'CURRENT',
  'ARRAY',
  'ROW',
  'FILTER',
  'WITHIN',
  'FOR',
  'ORDINALITY',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'LOCALTIME',
  'LOCALTIMESTAMP',
  'CONFLICT',
  'DO',
  'NOTHING'
]

const postgresqlFunctions: string[] = [
  // 聚合函数
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'ARRAY_AGG',
  'STRING_AGG',
  'JSON_AGG',
  'JSONB_AGG',
  'JSON_OBJECT_AGG',
  'JSONB_OBJECT_AGG',
  'XMLAGG',
  'BIT_AND',
  'BIT_OR',
  'BOOL_AND',
  'BOOL_OR',
  'EVERY',
  'REGR_COUNT',
  'REGR_SXX',
  'REGR_SYY',
  'REGR_SXY',
  'REGR_AVGX',
  'REGR_AVGY',
  'REGR_R2',
  'REGR_SLOPE',
  'REGR_INTERCEPT',
  'PERCENTILE_CONT',
  'PERCENTILE_DISC',
  'MODE',
  'RANGE_AGG',
  'RANGE_INTERSECT_AGG',
  // 窗口函数
  'ROW_NUMBER',
  'RANK',
  'DENSE_RANK',
  'NTILE',
  'LAG',
  'LEAD',
  'FIRST_VALUE',
  'LAST_VALUE',
  'NTH_VALUE',
  'CUME_DIST',
  'PERCENT_RANK',
  // 数学函数
  'ABS',
  'CEIL',
  'CEILING',
  'FLOOR',
  'ROUND',
  'TRUNC',
  'POWER',
  'SQRT',
  'CBRT',
  'EXP',
  'LN',
  'LOG',
  'MOD',
  'SIGN',
  'RANDOM',
  'SETSEED',
  'WIDTH_BUCKET',
  'GREATEST',
  'LEAST',
  'PI',
  'DEGREES',
  'RADIANS',
  'SIN',
  'COS',
  'TAN',
  'ASIN',
  'ACOS',
  'ATAN',
  'ATAN2',
  'COT',
  'SINH',
  'COSH',
  'TANH',
  'ASINH',
  'ACOSH',
  'ATANH',
  // 字符串函数
  'LENGTH',
  'CHAR_LENGTH',
  'CHARACTER_LENGTH',
  'BIT_LENGTH',
  'OCTET_LENGTH',
  'LOWER',
  'UPPER',
  'INITCAP',
  'TRIM',
  'LTRIM',
  'RTRIM',
  'BTRIM',
  'SUBSTRING',
  'SUBSTR',
  'LEFT',
  'RIGHT',
  'REPLACE',
  'REVERSE',
  'REPEAT',
  'CONCAT',
  'CONCAT_WS',
  'FORMAT',
  'LPAD',
  'RPAD',
  'SPLIT_PART',
  'POSITION',
  'STRPOS',
  'STARTS_WITH',
  'TRANSLATE',
  'OVERLAY',
  'REGEXP_MATCH',
  'REGEXP_MATCHES',
  'REGEXP_REPLACE',
  'REGEXP_SPLIT_TO_ARRAY',
  'REGEXP_SPLIT_TO_TABLE',
  'REGEXP_COUNT',
  'REGEXP_INSTR',
  'REGEXP_LIKE',
  'REGEXP_SUBSTR',
  'ASCII',
  'CHR',
  'MD5',
  'SHA224',
  'SHA256',
  'SHA384',
  'SHA512',
  'PGP_SYM_ENCRYPT',
  'PGP_SYM_DECRYPT',
  'ENCODE',
  'DECODE',
  'CONVERT',
  'CONVERT_FROM',
  'CONVERT_TO',
  'QUOTE_IDENT',
  'QUOTE_LITERAL',
  'QUOTE_NULLABLE',
  'TO_ASCII',
  'TO_HEX',
  'UNISTR',
  // 日期/时间函数
  'NOW',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'LOCALTIME',
  'LOCALTIMESTAMP',
  'CLOCK_TIMESTAMP',
  'STATEMENT_TIMESTAMP',
  'TRANSACTION_TIMESTAMP',
  'AGE',
  'DATE_TRUNC',
  'DATE_PART',
  'EXTRACT',
  'ISFINITE',
  'JUSTIFY_DAYS',
  'JUSTIFY_HOURS',
  'JUSTIFY_INTERVAL',
  'MAKE_DATE',
  'MAKE_TIME',
  'MAKE_TIMESTAMP',
  'MAKE_TIMESTAMPTZ',
  'MAKE_INTERVAL',
  'OVERLAPS',
  'TIMEOFDAY',
  'PG_SLEEP',
  'PG_SLEEP_FOR',
  'PG_SLEEP_UNTIL',
  'TO_DATE',
  'TO_TIMESTAMP',
  'TO_CHAR',
  'GENERATE_SERIES',
  'GENERATE_SUBSCRIPTS',
  // JSON 函数
  'TO_JSON',
  'TO_JSONB',
  'JSON_BUILD_OBJECT',
  'JSON_BUILD_ARRAY',
  'JSON_OBJECT',
  'JSON_ARRAY',
  'JSONB_BUILD_OBJECT',
  'JSONB_BUILD_ARRAY',
  'JSONB_OBJECT',
  'JSONB_ARRAY',
  'JSON_EXTRACT_PATH',
  'JSON_EXTRACT_PATH_TEXT',
  'JSONB_EXTRACT_PATH',
  'JSONB_EXTRACT_PATH_TEXT',
  'JSON_ARRAY_LENGTH',
  'JSONB_ARRAY_LENGTH',
  'JSON_EACH',
  'JSON_EACH_TEXT',
  'JSON_ARRAY_ELEMENTS',
  'JSON_ARRAY_ELEMENTS_TEXT',
  'JSONB_EACH',
  'JSONB_EACH_TEXT',
  'JSONB_ARRAY_ELEMENTS',
  'JSONB_ARRAY_ELEMENTS_TEXT',
  'JSON_OBJECT_KEYS',
  'JSONB_OBJECT_KEYS',
  'JSON_TYPEOF',
  'JSONB_TYPEOF',
  'JSON_STRIP_NULLS',
  'JSONB_STRIP_NULLS',
  'JSON_SET',
  'JSONB_SET',
  'JSON_INSERT',
  'JSONB_INSERT',
  'JSON_PRETTY',
  'JSONB_PRETTY',
  'JSON_CONTAINS',
  'JSONB_CONTAINS',
  'JSON_EXISTS',
  'JSONB_EXISTS',
  'JSONB_PATH_EXISTS',
  'JSONB_PATH_MATCH',
  'JSONB_PATH_QUERY',
  'JSONB_PATH_QUERY_ARRAY',
  'JSONB_PATH_QUERY_FIRST',
  'JSON_POPULATE_RECORD',
  'JSON_POPULATE_RECORDSET',
  'JSON_TO_RECORD',
  'JSON_TO_RECORDSET',
  'JSONB_POPULATE_RECORD',
  'JSONB_POPULATE_RECORDSET',
  'JSONB_TO_RECORD',
  'JSONB_TO_RECORDSET',
  'ROW_TO_JSON',
  'JSONB_AGG',
  'JSON_AGG',
  'JSONB_OBJECT_AGG',
  'JSON_OBJECT_AGG',
  // 数组函数
  'ARRAY_APPEND',
  'ARRAY_PREPEND',
  'ARRAY_CAT',
  'ARRAY_REMOVE',
  'ARRAY_REPLACE',
  'ARRAY_LENGTH',
  'ARRAY_LOWER',
  'ARRAY_UPPER',
  'ARRAY_POSITION',
  'ARRAY_POSITIONS',
  'ARRAY_DIMS',
  'ARRAY_NDIMS',
  'ARRAY_FILL',
  'ARRAY_TO_STRING',
  'STRING_TO_ARRAY',
  'UNNEST',
  'CARDINALITY',
  'TRIM_ARRAY',
  // 类型转换
  'CAST',
  'COALESCE',
  'NULLIF',
  'GREATEST',
  'LEAST',
  // 系统信息函数
  'VERSION',
  'CURRENT_USER',
  'CURRENT_ROLE',
  'SESSION_USER',
  'CURRENT_DATABASE',
  'CURRENT_SCHEMA',
  'CURRENT_SCHEMAS',
  'INET_CLIENT_ADDR',
  'INET_CLIENT_PORT',
  'INET_SERVER_ADDR',
  'INET_SERVER_PORT',
  'PG_BACKEND_PID',
  'PG_CANCEL_BACKEND',
  'PG_TERMINATE_BACKEND',
  'PG_BLOCKING_PIDS',
  'PG_CONF_LOAD_TIME',
  'PG_POSTMASTER_START_TIME',
  'PG_RELOAD_CONF',
  'PG_ROTATE_LOGFILE',
  'PG_DATABASE_SIZE',
  'PG_TABLE_SIZE',
  'PG_INDEXES_SIZE',
  'PG_TOTAL_RELATION_SIZE',
  'PG_SIZE_PRETTY',
  'PG_RELATION_SIZE',
  'PG_TABLESPACE_SIZE',
  'PG_GET_VIEWDEF',
  'PG_GET_RULEDEF',
  'PG_GET_TRIGGERDEF',
  'PG_GET_INDEXDEF',
  'PG_GET_CONSTRAINTDEF',
  'PG_GET_FUNCTIONDEF',
  'PG_GET_KEYWORDS',
  'PG_GET_SERIAL_SEQUENCE',
  'PG_COLUMN_SIZE',
  'PG_RELATION_FILENODE',
  'PG_RELATION_FILEPATH',
  'OBJ_DESCRIPTION',
  'SHOBJ_DESCRIPTION',
  'COL_DESCRIPTION',
  'PG_STAT_RESET',
  'PG_STAT_GET_BACKEND_IDSET',
  'HAS_ANY_COLUMN_PRIVILEGE',
  'HAS_COLUMN_PRIVILEGE',
  'HAS_DATABASE_PRIVILEGE',
  'HAS_FOREIGN_DATA_WRAPPER_PRIVILEGE',
  'HAS_FUNCTION_PRIVILEGE',
  'HAS_LANGUAGE_PRIVILEGE',
  'HAS_SCHEMA_PRIVILEGE',
  'HAS_SEQUENCE_PRIVILEGE',
  'HAS_SERVER_PRIVILEGE',
  'HAS_TABLE_PRIVILEGE',
  'HAS_TABLESPACE_PRIVILEGE',
  'HAS_TYPE_PRIVILEGE',
  'PG_HAS_ROLE',
  'PG_READ_FILE',
  'PG_READ_BINARY_FILE',
  'PG_STAT_FILE',
  'PG_LS_DIR',
  'PG_LS_LOGDIR',
  'PG_LS_WALDIR',
  'PG_LS_ARCHIVE_STATUSDIR',
  'PG_LS_TMPDIR',
  'TXID_CURRENT',
  'TXID_CURRENT_IF_ASSIGNED',
  'TXID_CURRENT_SNAPSHOT',
  'TXID_SNAPSHOT_XIP',
  'TXID_SNAPSHOT_XMAX',
  'TXID_SNAPSHOT_XMIN',
  'TXID_STATUS',
  'TXID_VISIBLE_IN_SNAPSHOT',
  // UUID 函数
  'GEN_RANDOM_UUID',
  // 全文搜索
  'TO_TSVECTOR',
  'TO_TSQUERY',
  'PLAINTO_TSQUERY',
  'PHRASETO_TSQUERY',
  'WEBSEARCH_TO_TSQUERY',
  'TSVECTOR_UPDATE_TRIGGER',
  'TSVECTOR_UPDATE_TRIGGER_COLUMN',
  'TS_HEADLINE',
  'TS_RANK',
  'TS_RANK_CD',
  'TS_LEXIZE',
  'TS_DEBUG',
  'TS_TOKEN_TYPE',
  'TS_PARSE',
  'TS_STAT',
  'TS_REWRITE',
  'TSQUERY_PHRASE',
  'SETWEIGHT',
  'NUMNODE',
  'STRIP',
  'TS_DELETE',
  // 网络地址函数
  'HOST',
  'TEXT',
  'ABBREV',
  'FAMILY',
  'NETMASK',
  'HOSTMASK',
  'NETWORK',
  'BROADCAST',
  'MASKLEN',
  'SET_MASKLEN',
  'INET_SAME_FAMILY',
  'INET_MERGE',
  'MACADDR8_SET7BIT',
  // 范围类型函数
  'ISEMPTY',
  'LOWER_INF',
  'UPPER_INF',
  'LOWER',
  'UPPER',
  'RANGE_MERGE',
  'ISEMPTY',
  'LOWER_INC',
  'UPPER_INC',
  'RANGE_MERGE',
  // 几何函数
  'POINT',
  'LINE',
  'LSEG',
  'BOX',
  'PATH',
  'POLYGON',
  'CIRCLE',
  'AREA',
  'CENTER',
  'DIAMETER',
  'HEIGHT',
  'ISCLOSED',
  'ISOPEN',
  'LENGTH',
  'NPOINTS',
  'PCLOSE',
  'POPEN',
  'RADIUS',
  'WIDTH',
  // XML 函数
  'XMLCOMMENT',
  'XMLCONCAT',
  'XMLELEMENT',
  'XMLFOREST',
  'XMLPARSE',
  'XMLPI',
  'XMLROOT',
  'XMLAGG',
  'XMLSERIALIZE',
  'XPATH',
  'XPATH_EXISTS',
  'TABLE_TO_XML',
  'QUERY_TO_XML',
  'CURSOR_TO_XML',
  'SCHEMA_TO_XML',
  'DATABASE_TO_XML',
  'TABLE_TO_XMLSCHEMA',
  'QUERY_TO_XMLSCHEMA',
  'CURSOR_TO_XMLSCHEMA',
  'SCHEMA_TO_XMLSCHEMA',
  'DATABASE_TO_XMLSCHEMA',
  'TABLE_TO_XML_AND_XMLSCHEMA',
  'QUERY_TO_XML_AND_XMLSCHEMA',
  // 其他常用函数
  'GENERATE_SERIES',
  'GENERATE_SUBSCRIPTS',
  'ORDINALITY',
  'ROWS_FROM'
]

const postgresqlDataTypes: string[] = [
  // 数值类型
  'SMALLINT',
  'INTEGER',
  'INT',
  'INT2',
  'INT4',
  'BIGINT',
  'INT8',
  'DECIMAL',
  'NUMERIC',
  'REAL',
  'FLOAT4',
  'DOUBLE',
  'PRECISION',
  'FLOAT8',
  'SMALLSERIAL',
  'SERIAL',
  'SERIAL2',
  'SERIAL4',
  'BIGSERIAL',
  'SERIAL8',
  'MONEY',
  // 字符类型
  'VARCHAR',
  'CHARACTER',
  'VARYING',
  'CHAR',
  'TEXT',
  'BPCHAR',
  'NAME',
  'CHARACTER VARYING',
  'CHARACTER VARYING(n)',
  // 二进制类型
  'BYTEA',
  // 日期/时间类型
  'DATE',
  'TIME',
  'TIMETZ',
  'TIMESTAMP',
  'TIMESTAMPTZ',
  'TIME WITHOUT TIME ZONE',
  'TIME WITH TIME ZONE',
  'TIMESTAMP WITHOUT TIME ZONE',
  'TIMESTAMP WITH TIME ZONE',
  'INTERVAL',
  // 布尔类型
  'BOOLEAN',
  'BOOL',
  // 几何类型
  'POINT',
  'LINE',
  'LSEG',
  'BOX',
  'PATH',
  'POLYGON',
  'CIRCLE',
  // 网络地址类型
  'INET',
  'CIDR',
  'MACADDR',
  'MACADDR8',
  // 位串类型
  'BIT',
  'BIT VARYING',
  'VARBIT',
  // 文本搜索类型
  'TSVECTOR',
  'TSQUERY',
  // UUID 类型
  'UUID',
  // JSON 类型
  'JSON',
  'JSONB',
  // XML 类型
  'XML',
  // 数组类型
  'ARRAY',
  'INT[]',
  'TEXT[]',
  'VARCHAR[]',
  'BOOLEAN[]',
  'JSONB[]',
  'UUID[]',
  // 范围类型
  'INT4RANGE',
  'INT8RANGE',
  'NUMRANGE',
  'TSRANGE',
  'TSTZRANGE',
  'DATERANGE',
  // 复合类型
  'OID',
  'REGCLASS',
  'REGPROC',
  'REGPROCEDURE',
  'REGOPER',
  'REGOPERATOR',
  'REGTYPE',
  'REGROLE',
  'REGNAMESPACE',
  'REGCONFIG',
  'REGDICTIONARY',
  'PG_LSN',
  'PG_SNAPSHOT',
  'TXID_SNAPSHOT',
  'XID',
  'XID8',
  'VOID'
]

const postgresqlSnippets: SqlSnippet[] = [
  { label: 'SELECT', insertText: 'SELECT $1 FROM $2', description: '基本查询语句' },
  { label: 'SELECT *', insertText: 'SELECT * FROM $1', description: '查询所有列' },
  { label: 'INSERT', insertText: 'INSERT INTO $1 ($2) VALUES ($3)', description: '插入数据' },
  { label: 'UPDATE', insertText: 'UPDATE $1 SET $2 = $3 WHERE $4', description: '更新数据' },
  { label: 'DELETE', insertText: 'DELETE FROM $1 WHERE $2', description: '删除数据' },
  { label: 'CREATE TABLE', insertText: 'CREATE TABLE $1 (\n  $2\n)', description: '创建表' },
  {
    label: 'ALTER TABLE',
    insertText: 'ALTER TABLE $1 ADD COLUMN $2 $3',
    description: '修改表结构'
  },
  { label: 'CREATE INDEX', insertText: 'CREATE INDEX $1 ON $2 ($3)', description: '创建索引' },
  {
    label: 'CREATE VIEW',
    insertText: 'CREATE VIEW $1 AS\nSELECT $2\nFROM $3',
    description: '创建视图'
  },
  { label: 'BEGIN', insertText: 'BEGIN;\n$1\nCOMMIT;', description: '事务块' },
  { label: 'EXPLAIN', insertText: 'EXPLAIN ANALYZE $1', description: '执行计划分析' },
  { label: 'COUNT', insertText: 'COUNT($1)', description: '计数聚合函数' },
  { label: 'COALESCE', insertText: 'COALESCE($1, $2)', description: '空值回退' },
  {
    label: 'CASE',
    insertText: 'CASE\n  WHEN $1 THEN $2\n  ELSE $3\nEND',
    description: '条件表达式'
  },
  { label: 'CAST', insertText: 'CAST($1 AS $2)', description: '类型转换' },
  { label: 'ILIKE', insertText: 'ILIKE $1', description: '不区分大小写模式匹配' },
  { label: 'SIMILAR TO', insertText: 'SIMILAR TO $1', description: 'SQL 标准正则匹配' },
  { label: 'IS NULL', insertText: 'IS NULL', description: '判空' },
  { label: 'IS NOT NULL', insertText: 'IS NOT NULL', description: '判非空' },
  {
    label: 'DISTINCT ON',
    insertText: 'DISTINCT ON ($1)',
    description: '按指定列去重（PostgreSQL 扩展）'
  },
  { label: 'RETURNING', insertText: 'RETURNING $1', description: '返回被修改行' },
  {
    label: 'ON CONFLICT',
    insertText: 'ON CONFLICT ($1) DO UPDATE SET $2 = EXCLUDED.$2',
    description: '冲突更新（UPSERT）'
  },
  { label: 'LATERAL', insertText: 'LATERAL ($1)', description: '横向子查询' },
  { label: 'WINDOW', insertText: 'OVER (PARTITION BY $1 ORDER BY $2)', description: '窗口函数' },
  { label: 'CTE', insertText: 'WITH $1 AS (\n  $2\n)\n$3', description: '公用表表达式（CTE）' },
  { label: 'CREATE DATABASE', insertText: 'CREATE DATABASE $1', description: '创建数据库' },
  { label: 'CREATE SCHEMA', insertText: 'CREATE SCHEMA $1', description: '创建模式' },
  { label: 'GRANT', insertText: 'GRANT $1 ON $2 TO $3', description: '授权' },
  { label: 'REVOKE', insertText: 'REVOKE $1 ON $2 FROM $3', description: '回收权限' },
  {
    label: 'COPY',
    insertText: "COPY $1 FROM '$2' WITH (FORMAT CSV)",
    description: '从文件导入数据'
  },
  { label: 'VACUUM', insertText: 'VACUUM ANALYZE $1', description: '清理并分析表' },
  {
    label: 'CREATE FUNCTION',
    insertText: 'CREATE FUNCTION $1($2)\nRETURNS $3 AS $$\nBEGIN\n  $4\nEND;\n$$ LANGUAGE plpgsql',
    description: '创建函数'
  },
  { label: 'DO', insertText: 'DO $$\nBEGIN\n  $1\nEND;\n$$', description: '匿名代码块' },
  {
    label: 'JSON_ARRAY_ELEMENTS',
    insertText: 'JSON_ARRAY_ELEMENTS($1)',
    description: '展开 JSON 数组'
  },
  { label: 'JSONB_EACH', insertText: 'JSONB_EACH($1)', description: '展开 JSONB 对象' },
  { label: 'STRING_AGG', insertText: "STRING_AGG($1, ',')", description: '字符串聚合' },
  { label: 'ARRAY_AGG', insertText: 'ARRAY_AGG($1 ORDER BY $2)', description: '数组聚合' },
  { label: 'GENERATE_SERIES', insertText: 'GENERATE_SERIES($1, $2)', description: '生成序列' },
  { label: 'UNNEST', insertText: 'UNNEST($1)', description: '展开数组' }
]

// ─── MySQL 补全配置 ───

const mysqlKeywords: string[] = [
  // DML
  'SELECT',
  'INSERT',
  'REPLACE',
  'UPDATE',
  'DELETE',
  'FROM',
  'WHERE',
  'JOIN',
  'INNER',
  'LEFT',
  'RIGHT',
  'OUTER',
  'CROSS',
  'STRAIGHT_JOIN',
  'ON',
  'USING',
  'AS',
  'INTO',
  'VALUES',
  'SET',
  'DEFAULT',
  'GROUP',
  'BY',
  'ORDER',
  'ASC',
  'DESC',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'WITH',
  'UNION',
  'ALL',
  'DISTINCT',
  'DISTINCTROW',
  // DDL
  'CREATE',
  'ALTER',
  'DROP',
  'TRUNCATE',
  'RENAME',
  'ADD',
  'MODIFY',
  'CHANGE',
  'COLUMN',
  'TABLE',
  'VIEW',
  'INDEX',
  'DATABASE',
  'SCHEMA',
  'FUNCTION',
  'PROCEDURE',
  'TRIGGER',
  'EVENT',
  'CONSTRAINT',
  'PRIMARY',
  'KEY',
  'FOREIGN',
  'REFERENCES',
  'UNIQUE',
  'CHECK',
  'NOT',
  'NULL',
  'AUTO_INCREMENT',
  'CASCADE',
  'RESTRICT',
  'IF',
  'EXISTS',
  'TEMPORARY',
  'ENGINE',
  'CHARSET',
  'COLLATE',
  'COMMENT',
  'PARTITION',
  'ALGORITHM',
  'LOCK',
  'GRANT',
  'REVOKE',
  'PRIVILEGES',
  'TO',
  'OPTION',
  'IDENTIFIED',
  'FLUSH',
  // DCL / 事务
  'START',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'SAVEPOINT',
  'RELEASE',
  'TRANSACTION',
  // 其他
  'EXPLAIN',
  'ANALYZE',
  'SHOW',
  'DESCRIBE',
  'USE',
  'CALL',
  'DECLARE',
  'LOOP',
  'WHILE',
  'REPEAT',
  'UNTIL',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'ELSEIF',
  'END',
  'IF',
  'COALESCE',
  'IFNULL',
  'NULLIF',
  'GREATEST',
  'LEAST',
  'CAST',
  'CONVERT',
  'BETWEEN',
  'IN',
  'LIKE',
  'REGEXP',
  'RLIKE',
  'IS',
  'AND',
  'OR',
  'XOR',
  'TRUE',
  'FALSE',
  'OVER',
  'PARTITION',
  'ROWS',
  'RANGE',
  'PRECEDING',
  'FOLLOWING',
  'CURRENT',
  'ROW',
  'LOCK',
  'FOR',
  'DUPLICATE'
]

const mysqlFunctions: string[] = [
  // 聚合函数
  'COUNT',
  'SUM',
  'AVG',
  'MIN',
  'MAX',
  'GROUP_CONCAT',
  'BIT_AND',
  'BIT_OR',
  'BIT_XOR',
  'STD',
  'STDDEV',
  'VARIANCE',
  // 窗口函数
  'ROW_NUMBER',
  'RANK',
  'DENSE_RANK',
  'NTILE',
  'LAG',
  'LEAD',
  'FIRST_VALUE',
  'LAST_VALUE',
  'NTH_VALUE',
  'CUME_DIST',
  'PERCENT_RANK',
  // 数学函数
  'ABS',
  'CEIL',
  'CEILING',
  'FLOOR',
  'ROUND',
  'TRUNCATE',
  'POW',
  'POWER',
  'SQRT',
  'EXP',
  'LN',
  'LOG',
  'LOG2',
  'LOG10',
  'MOD',
  'SIGN',
  'RAND',
  'PI',
  'DEGREES',
  'RADIANS',
  'SIN',
  'COS',
  'TAN',
  'ASIN',
  'ACOS',
  'ATAN',
  'ATAN2',
  'COT',
  'GREATEST',
  'LEAST',
  // 字符串函数
  'LENGTH',
  'CHAR_LENGTH',
  'CHARACTER_LENGTH',
  'BIT_LENGTH',
  'LOWER',
  'UPPER',
  'TRIM',
  'LTRIM',
  'RTRIM',
  'SUBSTRING',
  'SUBSTR',
  'MID',
  'LEFT',
  'RIGHT',
  'REPLACE',
  'REVERSE',
  'REPEAT',
  'CONCAT',
  'CONCAT_WS',
  'FORMAT',
  'LPAD',
  'RPAD',
  'INSTR',
  'LOCATE',
  'POSITION',
  'STRCMP',
  'ASCII',
  'CHAR',
  'MD5',
  'SHA1',
  'SHA2',
  'CONV',
  'HEX',
  'UNHEX',
  'QUOTE',
  'SOUNDEX',
  'SPACE',
  'ELT',
  'FIELD',
  'REGEXP_REPLACE',
  'REGEXP_SUBSTR',
  'REGEXP_INSTR',
  'REGEXP_LIKE',
  // 日期/时间函数
  'NOW',
  'CURDATE',
  'CURTIME',
  'CURRENT_DATE',
  'CURRENT_TIME',
  'CURRENT_TIMESTAMP',
  'SYSDATE',
  'DATE',
  'TIME',
  'YEAR',
  'MONTH',
  'DAY',
  'HOUR',
  'MINUTE',
  'SECOND',
  'DAYOFWEEK',
  'DAYOFMONTH',
  'DAYOFYEAR',
  'WEEK',
  'WEEKDAY',
  'QUARTER',
  'DATE_ADD',
  'DATE_SUB',
  'DATEDIFF',
  'TIMEDIFF',
  'DATE_FORMAT',
  'TIME_FORMAT',
  'STR_TO_DATE',
  'UNIX_TIMESTAMP',
  'FROM_UNIXTIME',
  'TIMESTAMPDIFF',
  'TIMESTAMPADD',
  'LAST_DAY',
  'EXTRACT',
  'ADDDATE',
  'SUBDATE',
  // JSON 函数
  'JSON_OBJECT',
  'JSON_ARRAY',
  'JSON_EXTRACT',
  'JSON_UNQUOTE',
  'JSON_SET',
  'JSON_INSERT',
  'JSON_REPLACE',
  'JSON_REMOVE',
  'JSON_CONTAINS',
  'JSON_CONTAINS_PATH',
  'JSON_KEYS',
  'JSON_LENGTH',
  'JSON_TYPE',
  'JSON_VALID',
  'JSON_ARRAYAGG',
  'JSON_OBJECTAGG',
  'JSON_TABLE',
  'JSON_MERGE',
  'JSON_MERGE_PATCH',
  'JSON_MERGE_PRESERVE',
  'JSON_PRETTY',
  'JSON_QUOTE',
  'JSON_SEARCH',
  // 类型转换
  'CAST',
  'CONVERT',
  'COALESCE',
  'IFNULL',
  'NULLIF',
  'GREATEST',
  'LEAST',
  // 系统信息函数
  'VERSION',
  'DATABASE',
  'SCHEMA',
  'CURRENT_USER',
  'USER',
  'SESSION_USER',
  'SYSTEM_USER',
  'CONNECTION_ID',
  'LAST_INSERT_ID',
  'ROW_COUNT',
  'FOUND_ROWS',
  'BENCHMARK',
  'SLEEP',
  'UUID',
  'UUID_SHORT'
]

const mysqlDataTypes: string[] = [
  // 数值类型
  'TINYINT',
  'SMALLINT',
  'MEDIUMINT',
  'INT',
  'INTEGER',
  'BIGINT',
  'DECIMAL',
  'NUMERIC',
  'FLOAT',
  'DOUBLE',
  'BIT',
  'BOOLEAN',
  'BOOL',
  'SERIAL',
  // 字符类型
  'CHAR',
  'VARCHAR',
  'TINYTEXT',
  'TEXT',
  'MEDIUMTEXT',
  'LONGTEXT',
  // 二进制类型
  'BINARY',
  'VARBINARY',
  'TINYBLOB',
  'BLOB',
  'MEDIUMBLOB',
  'LONGBLOB',
  // 日期/时间类型
  'DATE',
  'TIME',
  'DATETIME',
  'TIMESTAMP',
  'YEAR',
  // 枚举/集合类型
  'ENUM',
  'SET',
  // JSON 类型
  'JSON',
  // 空间类型
  'GEOMETRY',
  'POINT',
  'LINESTRING',
  'POLYGON',
  'MULTIPOINT',
  'MULTILINESTRING',
  'MULTIPOLYGON',
  'GEOMETRYCOLLECTION'
]

const mysqlSnippets: SqlSnippet[] = [
  { label: 'SELECT', insertText: 'SELECT $1 FROM $2', description: '基本查询语句' },
  { label: 'SELECT *', insertText: 'SELECT * FROM $1', description: '查询所有列' },
  { label: 'INSERT', insertText: 'INSERT INTO $1 ($2) VALUES ($3)', description: '插入数据' },
  {
    label: 'INSERT ON DUPLICATE',
    insertText: 'INSERT INTO $1 ($2) VALUES ($3)\nON DUPLICATE KEY UPDATE $4 = $5',
    description: '插入或按主键/唯一键更新（UPSERT）'
  },
  { label: 'UPDATE', insertText: 'UPDATE $1 SET $2 = $3 WHERE $4', description: '更新数据' },
  { label: 'DELETE', insertText: 'DELETE FROM $1 WHERE $2', description: '删除数据' },
  {
    label: 'CREATE TABLE',
    insertText: 'CREATE TABLE $1 (\n  $2\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4',
    description: '创建表'
  },
  {
    label: 'ALTER TABLE ADD',
    insertText: 'ALTER TABLE $1 ADD COLUMN $2 $3',
    description: '新增列'
  },
  {
    label: 'ALTER TABLE MODIFY',
    insertText: 'ALTER TABLE $1 MODIFY COLUMN $2 $3',
    description: '修改列定义'
  },
  { label: 'CREATE INDEX', insertText: 'CREATE INDEX $1 ON $2 ($3)', description: '创建索引' },
  {
    label: 'CREATE VIEW',
    insertText: 'CREATE VIEW $1 AS\nSELECT $2\nFROM $3',
    description: '创建视图'
  },
  {
    label: 'START TRANSACTION',
    insertText: 'START TRANSACTION;\n$1\nCOMMIT;',
    description: '事务块'
  },
  { label: 'EXPLAIN', insertText: 'EXPLAIN $1', description: '执行计划分析' },
  { label: 'COUNT', insertText: 'COUNT($1)', description: '计数聚合函数' },
  { label: 'IFNULL', insertText: 'IFNULL($1, $2)', description: '空值回退' },
  {
    label: 'CASE',
    insertText: 'CASE\n  WHEN $1 THEN $2\n  ELSE $3\nEND',
    description: '条件表达式'
  },
  { label: 'CAST', insertText: 'CAST($1 AS $2)', description: '类型转换' },
  { label: 'LIKE', insertText: 'LIKE $1', description: '模式匹配' },
  { label: 'IS NULL', insertText: 'IS NULL', description: '判空' },
  { label: 'IS NOT NULL', insertText: 'IS NOT NULL', description: '判非空' },
  { label: 'LIMIT', insertText: 'LIMIT $1, $2', description: '分页（偏移量, 数量）' },
  { label: 'SHOW CREATE TABLE', insertText: 'SHOW CREATE TABLE $1', description: '查看表 DDL' },
  {
    label: 'GROUP_CONCAT',
    insertText: "GROUP_CONCAT($1 SEPARATOR ',')",
    description: '字符串聚合'
  },
  {
    label: 'WINDOW',
    insertText: 'OVER (PARTITION BY $1 ORDER BY $2)',
    description: '窗口函数'
  },
  { label: 'CTE', insertText: 'WITH $1 AS (\n  $2\n)\n$3', description: '公用表表达式（CTE）' },
  { label: 'GRANT', insertText: "GRANT $1 ON $2 TO '$3'@'$4'", description: '授权' },
  { label: 'REVOKE', insertText: "REVOKE $1 ON $2 FROM '$3'@'$4'", description: '回收权限' },
  {
    label: 'CREATE PROCEDURE',
    insertText: 'DELIMITER $$\nCREATE PROCEDURE $1($2)\nBEGIN\n  $3\nEND$$\nDELIMITER ;',
    description: '创建存储过程'
  },
  {
    label: 'CREATE FUNCTION',
    insertText:
      'DELIMITER $$\nCREATE FUNCTION $1($2) RETURNS $3\nBEGIN\n  $4\n  RETURN $5;\nEND$$\nDELIMITER ;',
    description: '创建函数'
  },
  { label: 'JSON_EXTRACT', insertText: "JSON_EXTRACT($1, '$2')", description: '提取 JSON 字段' }
]

// ─── 配置注册表 ───

/** 按数据库类型索引的补全配置 */
export const SQL_COMPLETION_CONFIG: Record<DatabaseType, SqlCompletionConfig> = {
  postgresql: {
    keywords: postgresqlKeywords,
    functions: postgresqlFunctions,
    dataTypes: postgresqlDataTypes,
    snippets: postgresqlSnippets
  },
  mysql: {
    keywords: mysqlKeywords,
    functions: mysqlFunctions,
    dataTypes: mysqlDataTypes,
    snippets: mysqlSnippets
  }
}

/**
 * 获取指定数据库类型的补全配置
 * @param dbType - 数据库类型
 * @returns 补全配置对象；未注册类型返回空配置
 */
export function getCompletionConfig(dbType: DatabaseType): SqlCompletionConfig {
  return (
    SQL_COMPLETION_CONFIG[dbType] ?? {
      keywords: [],
      functions: [],
      dataTypes: [],
      snippets: []
    }
  )
}
